Tree: Add new auto check mode
BSI-Business-Systems-Integration-AG/org.eclipse.scout.docs pull request #180
Opened 2023-10-05 13:32 UTC by Knicksaas

2023-10-27 10:48 UTC, cguglielmo requested changes

2023-10-27 10:48 UTC, cguglielmo commented on code/widgets/org.eclipse.scout.jswidgets.ui.html/src/main/js/tree/TreePropertiesBox.ts
> +      this.tree.autoCheckStyle = event.newValue;
Use setter instead of assigning the property directly

2023-10-27 10:48 UTC, cguglielmo commented on code/widgets/org.eclipse.scout.jswidgets.ui.html/src/main/js/tree/TreePropertiesBoxModel.ts
> +      id: 'AutoCheckStyleField',
Move to CheckableStyleField to keep check boxes together

2023-10-27 10:48 UTC, cguglielmo commented on code/widgets/org.eclipse.scout.jswidgets.ui.html/src/main/js/treebox/AutoCheckStyleLookupCall.ts
> +    [Tree.AutoCheckStyle.AUTO_CHECK_CHILD_NODES, 'AUTO_CHECK_CHILD_NODES'],
Use small letters

2023-10-27 10:48 UTC, cguglielmo commented on code/widgets/org.eclipse.scout.jswidgets.ui.html/src/main/js/tree/TreePropertiesBoxModel.ts
>      {
Maybe add a string field that contains the ids of the checked nodes? This way we could easier verify that the state is correct

2023-11-24 16:01 UTC, Knicksaas commented
outdated, new PR: #186

2023-11-24 16:01 UTC, closed without merging