Calendar: add resource view
BSI-Business-Systems-Integration-AG/org.eclipse.scout.docs pull request #207
Opened 2024-01-19 16:04 UTC by Knicksaas

349852

2024-06-04 10:53 UTC, nsteger requested changes
as discussed, move to 24.2

2024-06-04 10:53 UTC, nsteger commented on code/widgets/org.eclipse.scout.widgets.client/src/main/java/org/eclipse/scout/widgets/client/services/lookup/CalendarsLookupCall.java
> +  private List<ICalendarDescriptor> m_calendars;
use also calendarDescriptor as variable name here? (I won't comment every occurence ;))

2024-06-04 10:53 UTC, nsteger commented on code/widgets/org.eclipse.scout.widgets.client/src/main/java/org/eclipse/scout/widgets/client/ui/forms/CalendarFieldForm.java
> +            return CollectionUtility.hashSet(CalendarMenuType.EmptySpace);
Not Calendar Menu Type, because should not appear as right click on the calendar, but as form menu

2024-06-04 10:53 UTC, nsteger commented on code/widgets/org.eclipse.scout.widgets.client/src/main/java/org/eclipse/scout/widgets/client/ui/forms/CalendarFieldForm.java
> +                .withName("Dyn #" + calendars.size())
Use better name

2024-06-04 10:53 UTC, nsteger commented on code/widgets/org.eclipse.scout.widgets.client/src/main/java/org/eclipse/scout/widgets/client/ui/forms/TreeAutoCheckStyleLookupCall.java
> +public class TreeAutoCheckStyleLookupCall extends LocalLookupCall<AutoCheckStyle> {
Never used? delete..

2024-06-04 13:57 UTC, nsteger commented
some releasenotes should be added

2024-07-04 07:17 UTC, Knicksaas commented
replaced by #237

2024-07-04 07:17 UTC, closed without merging